# Generated by Django 4.2.16 on 2026-05-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(db_index=True, max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Elemento de Despesa',
                'verbose_name_plural': 'Elementos de Despesa',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo', 'nome'], name='core_elemen_codigo_fd8007_idx')],
            },
        ),
    ]
