# Generated by Django 4.2.16 on 2026-05-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/', verbose_name='Arquivo PDF')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='documents/covers/', verbose_name='Imagem de Capa')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Número de Páginas')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
